### ISSUE TITLE
"NS not defined" error when using McCormick relaxation in v0.3.0

### ISSUE THREAD

**Issue by ca0h** [PSORLab/EAGO-notebooks#1]
Received 
`ERROR: LoadError: UndefVarError: NS not defined`
while running the example code in
[https://github.com/PSORLab/EAGO-notebooks/blob/master/notebooks/relaxation_plot_1d_explicit.ipynb](url)

OS: Windows 10
Julia Version: 1.2.0
Package versions: 
`EAGO v0.3.0`
 `IntervalArithmetic v0.16.1`

**Comment by mewilhel** [comment]
Thanks for the feedback and apologies for the delayed feedback. I apparently forgot to "watch" this repository.  I've updated this example in the repository.  The McCormick relaxations are now a submodule of EAGO. So in order to use MC, Diff, NS, etc., import the submodule with the statement "using EAGO.McCormick". Also, we're assuming that IntervalArithmetic is the Interval package so "EAGO.IntervalType -> Interval".
